name: Run Acceptance Tests
on:
  push:

permissions:
  contents: read

jobs:
  run-acc-tests:
    runs-on: ubuntu-latest
    env:
      VAULT_ACC: 1
      TEST_CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      TEST_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version-file: .go-version
          cache: true
      - name: Run Acceptance Tests
        run: CGO_ENABLED=0 go test -v -timeout=10m
      - name: Run Test Build
        run: go build -o bin/vault-plugin-secrets-cloudflare cmd/vault-plugin-secrets-cloudflare/main.go && ls -hl bin/